name: My Linux Workflow
on:
  workflow_dispatch:
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - id: first-step
        name: First Step
        run: |
          echo First Step
          json_data="{\"values\":\"Teste Valor\"}"
          echo json_data is $json_data
          (echo "json_data=$json_data") >> "$GITHUB_OUTPUT"
      - id: second-step
        name: Second Step
        run: |
          echo ${{ steps.first-step.outputs.json_data }}
