name: My First Workflow
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Node Install Dependencies
        run: npm ci
      - name: Install EsLint
        run: npm install eslint --save-dev
      - name: Install vitest
        run: npm install vitest --save-dev
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Deploy
        run: npm run build