name: My First Workflow
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Node Install Dependencies
        run: npm ci
      - name: Lint
        run: eslint --ext .jsx --fix src"
      - name: Test
        run: vitest run
      - name: Deploy
        run: vite build