name: My Linux Workflow
on:
  workflow_dispatch:
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - id: first-step
        name: First Step
        run: |
          echo First Step
          json_data="{\
            \"values\":\"Produção\"\
            }"
          echo json_data is $json_data
          (echo "json_data=$json_data") >> "$GITHUB_OUTPUT"
      - id: second-step
        name: Second Step
        run: |
          echo ${{ steps.first-step.outputs.json_data }}
          json_body='${{ steps.first-step.outputs.json_data }}'
          echo enviando json para a API
          curl -X POST "https://api.webhookinbox.com/i/y5ct5Ud1/in/"
            -H  "Content-Type: application/json"
            -d "$json_body"
          
